### ISSUE TITLE
Complex Market Conditions

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#362] opened 2018-03-23 10:19 UTC
I think we use have an ability to have complex Market conditions such as
- use combined AND & OR operator 
- groupings of conditions 

Example

((Exchange1H >3 OR Exchange 3H > 3) AND (Exchange 30M < Exchange 1H))

**Comment by Legedric** [comment] 2018-03-23 11:03
Duplicate of #175

**Closed by Legedric** 2018-03-23 11:03 UTC
