### ISSUE TITLE
Issue with switching from BTC to USDT base currency. 

### ISSUE THREAD

**Issue by dmzpkts** [Legedric/ptmagic#427] opened 2018-04-18 08:25 UTC
2018/04/17 20:38:17.348 INFO -
2018/04/17 20:38:17.736 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗
2018/04/17 20:38:17.736 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝
2018/04/17 20:38:17.740 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║
2018/04/17 20:38:17.740 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║
2018/04/17 20:38:17.740 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗
2018/04/17 20:38:17.740 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝
2018/04/17 20:38:17.740 INFO -                          Version 1.5.2
2018/04/17 20:38:17.740 INFO -
2018/04/17 20:38:18.555 INFO - Configuration loaded. Found 4 Market Trends, 6 Global Settings and 3 Single Market Settings.
2018/04/17 20:38:18.555 INFO - Profit Trailer found
2018/04/17 20:38:18.555 INFO - Trading directory found
2018/04/17 20:38:18.555 INFO - Checking for Pairs Properties file
2018/04/17 20:38:18.555 INFO - PAIRS.PROPERTIES found!
2018/04/17 20:38:18.555 INFO - Checking for DCA Properties file
2018/04/17 20:38:18.555 INFO - DCA.PROPERTIES found!
2018/04/17 20:38:18.569 INFO - Checking for Indicators Properties file
2018/04/17 20:38:18.569 INFO - INDICATORS.PROPERTIES found!
2018/04/17 20:38:18.606 INFO - Checking automated settings for presets...
2018/04/17 20:38:18.634 INFO - Prepared PAIRS.properties for 'Default'
2018/04/17 20:38:18.634 INFO - Prepared DCA.properties for 'Default'
2018/04/17 20:38:18.634 INFO - Prepared INDICATORS.properties for 'Default'
2018/04/17 20:38:18.634 INFO - Checking market trends every 5 minutes...
2018/04/17 20:38:18.818 INFO -
2018/04/17 20:38:18.841 INFO - ##########################################################
2018/04/17 20:38:18.841 INFO - #********************************************************#
2018/04/17 20:38:18.841 INFO - Starting market trend check with Version 1.5.2
2018/04/17 20:38:19.541 INFO - Loading current Profit Trailer properties files...
2018/04/17 20:38:19.541 INFO - Files loaded - P (109 lines) - D (45 lines) - I (21 lines).
2018/04/17 20:38:19.541 INFO - Loading Single Market Setting Summaries...
2018/04/17 20:38:19.624 INFO - Single Market Setting Summaries loaded.
2018/04/17 20:38:19.658 INFO - Profit Trailer Version 1.x.y detected...
2018/04/17 20:38:19.848 INFO - CoinMarketCap - Getting market data...
2018/04/17 20:38:19.988 INFO - CoinMarketCap - Market data received for 100 currencies
2018/04/17 20:38:20.510 INFO - CoinMarketCap - 24h market data rebuilt.
2018/04/17 20:38:20.522 INFO - CoinMarketCap - Market data saved.
2018/04/17 20:38:20.522 INFO - CoinMarketCap - Market data cleaned.
2018/04/17 20:38:20.546 INFO - Binance - Getting market data...
2018/04/17 20:38:21.142 INFO - Binance - Market data received for 301 currencies
2018/04/17 20:38:21.172 INFO - Binance - Checking first seen dates for 8 markets. This may take a while...
2018/04/17 20:38:21.288 INFO - Binance - Recreating market data for 8 markets over 6h 27m 22s. This may take a while... 
2018/04/17 20:38:21.584 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 106
2018/04/17 20:38:21.761 ERROR - Unable to get data from Binance with URL 'https://api.binance.com/api/v1/klines?interval=1m&symbol=USDTUSDT&endTime=1524022701334&limit=388'! - Code: -1121 - Message: Invalid symbol.
2018/04/17 20:38:24.627 INFO - Binance - Ticks completed.
2018/04/17 20:38:24.744 INFO - Binance - Creating initial market data ticks. This may take another while...
2018/04/17 20:38:24.767 FATAL - Exception while getting data for 'ADAUSDT': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.CheckForMarketDataRecreation(String mainMarket, Dictionary`2 markets, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 303
   at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 81
2018/04/17 20:38:24.870 ERROR - Unable to contact Binance for fresh market data. Trying again in 5 minute(s).

**Comment by Legedric** [comment] 2018-04-18 08:36
Duplicate of #415

**Closed by Legedric** 2018-04-18 08:36 UTC
