### ISSUE TITLE
Manage SMS Critical Error

### ISSUE THREAD

**Issue by chriswong23** [Legedric/ptmagic#408] opened 2018-04-09 04:00 UTC
After  upgrading from v1.5.0 to v1.5.1, the "Manage SMS" page does not work. I have tried to remove all my SMS and leaving just 1 basic block of settings but it still does not work.

![image](https://user-images.githubusercontent.com/2024989/38478791-83b4eb3c-3bed-11e8-843a-1191b674bf21.png)

**Comment by Legedric** [comment] 2018-04-09 04:07
Duplicate of #403

**Closed by Legedric** 2018-04-09 04:07 UTC
