### ISSUE TITLE
Forced to rename configuration filenames

### ISSUE THREAD

**Issue by yuvalbar84** [Legedric/ptmagic#5] opened 2018-02-16 22:22 UTC
On linux, my files are named like so:
PAIRS.properties , DCA.properties ...
as you know, linux is case sensitive, and your code tries to open PAIRS.PROPERTIES, even though i changed it to PAIRS.properties in the analyzer.settings .

**Comment by Spottycat** [comment] 2018-02-17 00:28
I can confirm that. I renamed the files and PTMagic worked correctly. But as PT cannot read those renamed files, it doesn't work as of yet. 

A workaround would probably be symlinks, but thats no permanent solution. 

Thanks in advance

**Comment by crypto-design** [comment] 2018-02-17 01:09
I also have filename error on Ubuntu - File PAIRS.PROPERTIES not found in /var/opt/pt/trading/PAIRS.PROPERTIES because Ubuntu is case sensitive...
Please make update

**Comment by Legedric** [comment] 2018-02-17 07:03
Usually we did everything case insensitive in PT Magic but THIS one thing slipped through somehow.
I will work on a fix later today.

**Comment by Legedric** [comment] 2018-02-17 12:51
This issue is fixed in release 1.0.1

**Closed by Legedric** 2018-02-17 12:51 UTC
Labels: confirmed
