### ISSUE TITLE
BINANCE AUTO BLack List

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#195] opened 2018-02-24 21:30 UTC
Could we have a script like this onside PT Magic.
https://github.com/bennettca/binance-auto-blacklist

It could not run together since it will compete with PTMagic to write atributes on the Pair.propertires file..

**Comment by Zamboniman** [comment] 2018-02-24 21:53
See Issue #107

**Comment by Legedric** [comment] 2018-02-25 08:54
Duplicate of #107

**Closed by Legedric** 2018-02-25 08:54 UTC
