### ISSUE TITLE
Errors after update from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by jochiewashere** [Legedric/ptmagic#401] opened 2018-04-08 08:45 UTC
After the update of PT magic from 1.5.0 to 1.5.1 i get the message in the red box: Dashboard (Top) update failed!
i followed the update instructions and both scripts are running without a error
any ideas what i can check ?
I tried reinstall, restart the PTmagic and reboot server
I didn't had any problems with 1.5.0
its only the Dashboard (TOP)... when i stop the monitor i get more messages, so most of the monitor scripts are working. Anyone else with this error (or bug)

**Comment by Legedric** [comment] 2018-04-08 08:58
Duplicate of #396

**Closed by Legedric** 2018-04-08 08:58 UTC
