### ISSUE TITLE
Nested conditions for single market conditions  

### ISSUE THREAD

**Issue by cryptotamilan** [Legedric/ptmagic#324] opened 2018-03-16 07:01 UTC
Optinto have nested conditions in the single market settings would be very useful,ex: exchange1H>1 and(exchange2h<. 5 or exchange3h<. 7). If this would help analyze marker trends in a better by deciding based on any one positive trend but at த same time make sure it matches a critical trend criteria

**Comment by cybermizrach** [comment] 2018-03-23 10:18
I think we use have an ability to use combined AND & OR operator and groupings of conditions such as

((Exchange1H >3 OR Exchange 3H > 3) AND  (Exchange 30M < Exchange 1H))

**Comment by Legedric** [comment] 2018-03-23 11:03
Duplicate of #175

**Closed by Legedric** 2018-03-23 11:03 UTC
