### ISSUE TITLE
Multiple comments in INDICATORS.properties file

### ISSUE THREAD

**Issue by jamesblackjr** [Legedric/ptmagic#63] opened 2018-02-20 02:21 UTC
I have several comments like this in my INDICATORS.properties file, every minute it adds another:

```
# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:21 PM
# ####################################

# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:20 PM
# ####################################

# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:19 PM
# ####################################
```

**Comment by Legedric** [comment] 2018-02-20 05:36
Thanks, that seems to be the root cause of issue #46. I still have to figure out what causes this. Do you see that only in your indicators or also the other files?

**Comment by jamesblackjr** [comment] 2018-02-20 05:49
yes just the INDICATORS file.

**Comment by Legedric** [comment] 2018-02-20 11:19
What does the header of your PAIRS file look like? Because that's where the check for the active setting happens in.

**Comment by Legedric** [comment] 2018-02-20 11:23
Also: Is this the indicators file from your PT/trading directory? If so, how does the one in "_presets" look. Same issue?

**Comment by jamesblackjr** [comment] 2018-02-20 13:23
I'm looking at the one in the PT/trading directory.  The one in _presets is not changed.

**Comment by Legedric** [comment] 2018-02-20 13:24
No changed means it has those headers, too or not?

**Comment by Legedric** [comment] 2018-02-21 20:21
Closing this issue as it seems the cause is the same as for #46

**Closed by Legedric** 2018-02-21 20:21 UTC
Labels: in review
