### ISSUE TITLE
PTM again hung up

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#530] opened 2018-05-23 14:18 UTC
![default](https://user-images.githubusercontent.com/33903011/40430219-daa55612-5ece-11e8-8fb3-c96cae9a6b9d.PNG)
and nothing happens.

**Comment by Legedric** [comment] 2018-05-23 15:21
Duplicate of #528

**Closed by Legedric** 2018-05-23 15:21 UTC

**Comment by clippart** [comment] 2018-05-24 01:00
stop stop stop
So how much is this interval? I waited 1 hour! and PTM and hung in a state that the PT is not running. A PT launched

**Comment by Legedric** [comment] 2018-05-24 05:09
Read what I wrote in issue #528... The part where PTM rechecks for PT to be running on the next interval only happens when PTM SUCCESSFULLY started for the first time.

In your case the startup check is not positive so it terminates itself.
