### ISSUE TITLE
Couple of errors

### ISSUE THREAD

**Issue by tyriekfv** [Legedric/ptmagic#57] opened 2018-02-19 23:48 UTC
When using PTmagic 1.02 on Binance with ETH.  Coin is listed as BTC instead of ETH.  Balance is also not correct.  Balance in Binance is $200 USD
![ethbtc](https://user-images.githubusercontent.com/36649530/36401392-14741856-158c-11e8-9108-10b909ab8490.jpg)

**Comment by Legedric** [comment] 2018-02-20 05:31
The display on the top will be fixed in the next release (duplicate of #31)

The balance has to be adjusted manually, PT Magic has no access to your balance so you have to enter the start balance in your settings.

**Closed by Legedric** 2018-02-20 05:31 UTC
