### ISSUE TITLE
BTC value incorrect after upgrade to v1.5.2

### ISSUE THREAD

**Issue by tailorgd** [Legedric/ptmagic#417] opened 2018-04-12 14:03 UTC
BTC value incorrect after upgrade to v1.5.2

Currently, BTC is valued at 7696.00 and PT Magic shows the value as 6855.01

**Comment by tailorgd** [comment] 2018-04-13 00:09
I compared it to both Profit Trailer and the price directly on Binance, which were both correct.

**Comment by angelsomar** [comment] 2018-04-13 03:35
I confirm that it is true, not only BTC in ETH is also the error

in console it goes well but it shows badly in the monitor

**Comment by Legedric** [comment] 2018-04-13 08:05
I need screenshots, please. For me everything looks fine.
![image](https://user-images.githubusercontent.com/8308141/38723641-0bf58170-3f02-11e8-9a9a-dd5f88e85c31.png)
![image](https://user-images.githubusercontent.com/8308141/38723678-21c1d184-3f02-11e8-996d-9ef4d65f4328.png)

Please provide the same set of screenshots so I am able to see what may be the cause for this issue.

**Comment by angelsomar** [comment] 2018-04-13 12:30
Magic Updated the value but not the actual

![image](https://user-images.githubusercontent.com/36096512/38734739-481d0b48-3eec-11e8-92f3-cb6674575a47.png)

**Comment by Legedric** [comment] 2018-04-19 05:34
This should be fixed with the next release. If not, please reopen this issue.

**Closed by Legedric** 2018-04-19 05:34 UTC
