### ISSUE TITLE
Checking triggers for 'EndOfTheWorld' 'The given key was not present in the dictionary'

### ISSUE THREAD

**Issue by jeffcpullen** [Legedric/ptmagic#67] opened 2018-02-20 06:26 UTC
I'm deploying PTMagic in a docker container will full access to the PTTrailer trading and logs folder **only** and getting the following error. The app doesn't have access to the PTTrailer root directory (if it works it should limit a lot of the fears surrounding API key access). 

The app starts and synchronized with the exchanges then fails here. Thoughts?

```
2018/02/20 06:12:47.506 INFO - Built average market trend change 'CMC24h' (3.22% in 1440 minutes) for 50 markets. 
2018/02/20 06:12:47.509 INFO - Global market trends built. 
2018/02/20 06:12:47.510 INFO - Checking global settings triggers... 
2018/02/20 06:12:47.511 INFO - Checking triggers for 'EndOfTheWorld'... 
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 236
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 177
/bin/sh: line 1:     5 Aborted                 (core dumped) dotnet PTMagic.dll
```

**Comment by Legedric** [comment] 2018-02-20 07:19
Duplicate of #35

**Closed by Legedric** 2018-02-20 07:19 UTC
