### ISSUE TITLE
[Bug] Market Analyzer - single market setting tooltip

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#332] opened 2018-03-19 19:21 UTC
On the Market Analyzer page:

The tooltip for the little "warning" icon next to the market names (for anything with an applied single market setting) doesn't work if the list has been sorted by one of the columns (last price, volume, trends).

Tried in both Chrome and Firefox.

**Comment by Legedric** [comment] 2018-03-19 19:25
Duplicate of #308

**Closed by Legedric** 2018-03-19 19:25 UTC

**Comment by HojouFotytu** [comment] 2018-03-19 19:30
Whoops!   ;)
