### ISSUE TITLE
Editing preset file does not work, problem saving

### ISSUE THREAD

**Issue by djbadders** [Legedric/ptmagic#540] opened 2018-05-29 18:29 UTC
Hi I love that you have added editing the preset files to PTM, but using 2.0.1 I can edit the files click "Save" and get the confirmation message, but the files have not changed on disk. I have 4 installations and all are doing the same. Nothing logged in the logs either, I think it may be a bug.

**Comment by Aussiebjl** [comment] 2018-05-30 03:52
Just did a test on mine, all 3 presets edit and save from the GUI with no issues.  This could potentially be a local filesystem permissions issue and might be worthwhile checking your OS. Did you maybe create the preset files as a different user to the one you are now using to run PT Magic? If you are using Linux CHMOD 0777 (everyone read/write/execute) the 3x preset files to test then lockdown the permissions as required.

**Comment by Legedric** [comment] 2018-05-30 05:17
@djbadders Make sure that your monitor is poiting to the correct PTMagicBasePath (appsettings.json) as this defines where to look for the preset files.

**Comment by djbadders** [comment] 2018-05-30 22:02
@Legedric checked the PTMagicBasePath and all is good; files open up fine for editting, they just don't save. 

@Aussiebjl Tried the permissions change, but no change in behaviour.

Very odd. Any other ideas? I guess it may need more logging in this area.

**Comment by Legedric** [comment] 2018-05-31 08:50
Not really as I cannot reproduce your issue.
As you are the only one that has this issue (at least as far as I am aware of) it seems to be a local issue with your setup.

If PTM encounters a problem while saving the presets file you will get error feedback directly in the monitor. If PTM says it saved the file than everything worked fine for the application itself. So as long as you do not see any error message popping up it wouldn't help to have more logging in that area.

**Comment by djbadders** [comment] 2018-06-04 18:32
Ok so I get all the confirmations but no save; in this example I have added a comment "# test" to the file.

![image](https://user-images.githubusercontent.com/34887832/40934748-b99c2316-682d-11e8-860e-dad94a8cb2d0.png)

![image](https://user-images.githubusercontent.com/34887832/40934797-dfc046a8-682d-11e8-88b2-40a9a1330305.png)

![image](https://user-images.githubusercontent.com/34887832/40934811-ec56c37e-682d-11e8-8568-717d9b918685.png)

The "#Test" line is missing.

No errors, but no update. Permissions seem fine. Very strange.

**Comment by Legedric** [comment] 2018-06-05 06:29
I added some better feedback and debug logging to this area for the next release.

**Comment by DaveBaddeley** [comment] 2018-06-05 13:52
Thanks, will upgrade and retest

**Comment by djbadders** [comment] 2018-06-05 18:59
So the error is "ERROR - Error saving preset file: /home/dave_j_baddeley/PTMagic/_presets/Default/INDICATORS.PROPERTIES" , interestingly my properties files have a lower case ".properties", not the uppercase shown in the path. Not sure when this changed?

**Comment by djbadders** [comment] 2018-06-05 19:23
So renamed the files to all capitals and then it saved, but when trying to edit the file again the UI then can't seem to find the file and opens a blank editor.

**Comment by Legedric** [comment] 2018-06-06 04:05
Thanks, this will be fixed in the next release.

**Closed by Legedric** 2018-06-06 04:05 UTC
Labels: waiting for user

**Comment by DaveBaddeley** [comment] 2018-06-07 10:56
Thank you
