### ISSUE TITLE
PTMagic Raspberry

### ISSUE THREAD

**Issue by siquenique** [Legedric/ptmagic#243] opened 2018-03-01 00:01 UTC
Hi,

I am trying to install PTMagic in a raspberry but as it seems there is no dotnet SDK for raspberry the monitor doesn't work.

Did anyone found a way to use raspberry?

**Comment by Legedric** [comment] 2018-03-01 04:10
Duplicate of #81

**Closed by Legedric** 2018-03-01 04:10 UTC
