### ISSUE TITLE
Dotnet Issue

### ISSUE THREAD

**Issue by carllewis1980** [Legedric/ptmagic#508] opened 2018-05-12 08:52 UTC
I have an issue that whenever i start Magic, Dotnet stops working and crashes. error on magic is...

C:\Users\Administrator\Desktop\PROFIT TRAILER AND MAGIC\MAGIC\PTMagic>dotnet PTM
agic.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Us
ers\Administrator\Desktop\PROFIT TRAILER AND MAGIC\MAGIC\PTMagic\nlog.config'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOption
s options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials,
 IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofO
bjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settin
gs, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContex
t inputContext)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreE
rrors, LogFactory logFactory)
   at NLog.Extensions.Logging.ConfigureExtensions.ConfigureNLog(ILoggerFactory l
oggerFactory, String configFileRelativePath)
   at Globals.ServiceHelper.BuildLoggerService(String basePath) in D:\Tools\PTMa
gic\Globals\ServiceHelper.cs:line 27
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs
:line 17

C:\Users\Administrator\Desktop\PROFIT TRAILER AND MAGIC\MAGIC\PTMagic>pause
Press any key to continue . . .

**Comment by Legedric** [comment] 2018-05-12 11:47
Duplicate of #453

**Closed by Legedric** 2018-05-12 11:47 UTC
