### ISSUE TITLE
Error when run Start PTMagic.cmd - Fixed

### ISSUE THREAD

**Issue by Crypto108** [Legedric/ptmagic#14] opened 2018-02-17 23:53 UTC
I have everything in place. Path etc.
But in end Start PTMagic.cmd gives:

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: XMRBTC
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 580
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 177

**Comment by Crypto108** [comment] 2018-02-17 23:57
I'm using PTMagic 1.0.1, Windows version. I can start Monitor no problem, just the "Start PTMagic.cmd" gives this error.

**Comment by Crypto108** [comment] 2018-02-17 23:58
Note, that "D:\Tools\PTMagic\PTMagic\" is not my path, I'm on C drive

**Comment by Crypto108** [comment] 2018-02-18 00:18
I fixed it, by disabling my whitelist in PAIRS.properties (Profittrailer).
And change back to "ALL_enabled_pairs = ALL"
Now everything is starting fine.
Thank you @Legedric for the tool. You can mark it as solved.

**Comment by Legedric** [comment] 2018-02-18 09:35
@Crypto108 Could you please post your old whitelist here?
It is good to know that setting it to "ALL" is a workaround but it would help us to identify the root cause of this issue :)

**Comment by TwixRaider** [comment] 2018-02-18 10:46
Please check if you have the pair XMR-BTC twice in your white list. If so please delete one entry and it should work...

**Comment by Crypto108** [comment] 2018-02-18 14:03
@TwixRaider You were absolutely right, I got the double XMRBTC in the whitelist. Wow.

Whitelist from PAIRS.properties:

ALL_enabled_pairs = ADABTC, ADXBTC, AIONBTC, AMBBTC, ARNBTC, ARKBTC, ASTBTC, BATBTC, BCCBTC, BCPTBTC,BRDBTC, BTSBTC, BQXBTC, CDTBTC, CMTBTC, CTRBTC, DASHBTC, DLTBTC, DNTBTC, FUELBTC, EDOBTC, ELFBTC, ENGBTC, ENJBTC, ETCBTC, ETHBTC, EOSBTC, EVXBTC, FUNBTC, GTOBTC, GVTBTC, HSRBTC, ICNBTC, IOTABTC, KNCBTC, KMDBTC, LINKBTC, LRCBTC, LSKBTC, LTCBTC, MCOBTC, MDABTC, MTHBTC, MODBTC, NAVBTC, NEBLBTC, NEOBTC, NULSBTC, OAXBTC, OMGBTC, OSTBTC, POEBTC, POWRBTC, QSPBTC, RCNBTC, RDNBTC, REQBTC, SNGLSBTC, SNMBTC, SNTBTC, STORJBTC, STRATBTC, SUBBTC, TRIGBTC, TRXBTC, VIBBTC, WABIBTC, WAVESBTC, WINGSBTC, XLMBTC, XMRBTC, XMRBTC, XRPBTC, XVGBTC, ZECBTC, ZRXBTC

**Comment by TwixRaider** [comment] 2018-02-18 14:19
OK, there are 2 entries XMRBTC near the end. Please remove one of them and you can use the white list again.

**Comment by Legedric** [comment] 2018-02-18 15:04
Thanks, the issue will be fixed in 1.0.2 anyway :)

**Closed by Legedric** 2018-02-18 15:04 UTC
Labels: in review
