### ISSUE TITLE
‼️Feature Request - COIN blacklist by age….

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#340] opened 2018-03-20 15:23 UTC
COIN blacklist by age…. 

ProfitTrailer - Binance Auto Blacklist

Automatcally checks for new Binance listings and enables sell-only mode for pairs in ProfitTrailer. All newly listed coins will be set to sell-only mode in your PAIRS.properties file. If you are using PT-Feeder, your SomOnlyPairs in appsettings.json will be updated.

Configuration

Modify these settings in the blacklist.properties file:

enabled = true (enable/disable this tool while it's running)
interval = 5 (interval in minutes to check for new Binance listings)
market = BTC (the market your bot is currently in)
days = 14 (automatically disable coins that have only been listed for less than 14 days)
clear = false (if true, disable sell-only mode for a newly listed coin once it has been listed for at least the days defined above)

Source: https://github.com/bennettca/binance-auto-blacklist

**Comment by Legedric** [comment] 2018-03-20 15:48
Duplicate of #107

**Closed by Legedric** 2018-03-20 15:48 UTC
