### ISSUE TITLE
PTMagic starting problem

### ISSUE THREAD

**Issue by Mikel399** [Legedric/ptmagic#531] opened 2018-05-23 19:57 UTC
Hello there,
I've intalled PTMagic 2.0.1 I tried to run it and I get this error
I hope you can help me.
Thanks,
MikeL

![image](https://user-images.githubusercontent.com/39569837/40447777-898223c8-5e88-11e8-8cdf-037c3da9e4b3.jpg)

**Comment by Legedric** [comment] 2018-05-24 05:10
Duplicate of #450

**Closed by Legedric** 2018-05-24 05:10 UTC

**Comment by Mikel399** [comment] 2018-05-26 20:57
how do I change all this? Im not an expert

**Comment by Legedric** [comment] 2018-05-27 08:30
Wait for the next release of PTM and it will include instructions on this.

**Comment by Mikel399** [comment] 2018-05-27 14:02
Thank you so much for taking the time to reply


Sent from my iPhone

On May 27, 2018, at 1:30 AM, Legedric <notifications@github.com<mailto:notifications@github.com>> wrote:


Wait for the next release of PTM and it will include instructions on this.
