### ISSUE TITLE
Monitor error

### ISSUE THREAD

**Issue by Auhunter61** [Legedric/ptmagic#112] opened 2018-02-21 15:39 UTC
getting this issue and not sure how to fix

C:\Users\Auhunter\Desktop\PTMagic 1.0.3\PTMagic>dotnet Monitor/Monitor.dll

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'settings.general.json' was not found and is not optional. The physical path is 'C:\Users\Auhunter\Desktop\PTMagic 1.0.3\settings.general.json'.
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 32

C:\Users\Auhunter\Desktop\PTMagic 1.0.3\PTMagic>pause
Press any key to continue . . .

**Comment by Legedric** [comment] 2018-02-21 15:47
Duplicate of #111

**Closed by Legedric** 2018-02-21 15:47 UTC
