### ISSUE TITLE
Daily freeze of PTMagic and monitor

### ISSUE THREAD

**Issue by Peet911** [Legedric/ptmagic#268] opened 2018-03-02 19:38 UTC
Every day one or two times a freeze of PTM.
I asked around in our Telegram group and several others hace this problem to.
result is also a flatline in markettrend
Screenshot time is 20:30 ( PM). so it stopped again at 19:47

![knipsel1](https://user-images.githubusercontent.com/36714194/36918246-923a46ae-1e59-11e8-887a-9f154a740cd3.PNG)
![knipsel2](https://user-images.githubusercontent.com/36714194/36918247-925b1942-1e59-11e8-9d42-147bb6fa9bac.PNG)
![knipsel3](https://user-images.githubusercontent.com/36714194/36918248-9272a31e-1e59-11e8-8bd8-02e515a3018b.PNG)

**Comment by Amelsfort** [comment] 2018-03-03 08:37
Same here! I noticed the last run time was a long time ago, so I checked the bot and there was no logging since that time. After a restart, it works for again for some time. Before hanging again.

**Comment by Juleseck** [comment] 2018-03-03 09:44
Same here! Have to restart ptmagic around 3 times daily.

**Comment by Legedric** [comment] 2018-03-03 12:24
How many markets are you all using?
In the log from @Peet911 I can see he is running 110 markets. Are you all running like 100+ markets or less than that?

**Comment by Amelsfort** [comment] 2018-03-03 12:28
I'm running on Binance and it's using 120 markets. It started doing that by default.

**Comment by Legedric** [comment] 2018-03-03 12:33
Ok I will try setting up my bot for Binance with full market list and see if I am able to reproduce this.

**Comment by Peet911** [comment] 2018-03-03 17:43
I  use the standard markets. didnt change a thing, only added a 6 hours check. But before that it also froze

**Comment by agaji** [comment] 2018-03-03 21:46
Im on Binance and have the freezing too

**Comment by GriffinB123** [comment] 2018-03-04 05:28
Add my name to the list of people getting the "did the bot hang?" notifications.  Running two PT bots, and two instances of PT Magic on a single Windows VPS.  Only one of the PT bots is getting the error.
![screen shot 2018-03-03 at 9 27 17 pm](https://user-images.githubusercontent.com/36783772/36942550-cd50244a-1f29-11e8-9824-705ff32a90f3.png)
![screen shot 2018-03-03 at 9 26 45 pm](https://user-images.githubusercontent.com/36783772/36942551-cd7619ca-1f29-11e8-8a21-5868916ad862.png)

**Comment by GriffinB123** [comment] 2018-03-04 05:38
Nevermind.  Both of my bots are hanging.
![screen shot 2018-03-03 at 9 32 12 pm](https://user-images.githubusercontent.com/36783772/36942602-31541464-1f2b-11e8-80ec-dd6ea72b0d57.png)

It could be that my VPS doesn't have enough memory, so I will upgrade that now, to see if it helps.
![screen shot 2018-03-03 at 9 37 41 pm](https://user-images.githubusercontent.com/36783772/36942603-33509f58-1f2b-11e8-98ca-c2a14504d862.png)

**Comment by Legedric** [comment] 2018-03-04 06:12
@GriffinB123 That's PT hanging right there, not PT Magic. So there is nothing I can do about that as I am only working on PT Magic.

**Comment by GriffinB123** [comment] 2018-03-04 06:44
@Legedric 

Yes, PT is the program hanging, but it only happens when PT Magic is running.  If I close PT Magic, PT runs without any issues.

**Comment by GriffinB123** [comment] 2018-03-04 06:45
And I upgraded my VPS (double the RAM), and am still getting the same issue.
![screen shot 2018-03-03 at 10 39 07 pm](https://user-images.githubusercontent.com/36783772/36942940-836aa368-1f34-11e8-9d6a-659e2474a9c7.png)
![screen shot 2018-03-03 at 10 38 46 pm](https://user-images.githubusercontent.com/36783772/36942941-838116d4-1f34-11e8-9ed2-e5453fe5113e.png)

**Comment by Legedric** [comment] 2018-03-04 06:52
@GriffinB123 PT Magic barely consumes any resources (<100MB RAM) so it is quite impossible for it to affect the processing of PT itself just because of resources.

And as hundreds of users are using PTM just fine without Profit Trailer crashing, I assume the problem here is out of scope for us to fix.

**Comment by Legedric** [comment] 2018-03-04 06:52
I was able to reproduce the PT Magic freeze and it seems to happen mostly on Binance when you are running many markets (100+, maybe less). I am yet unable to find the cause for this but I will work on something that prevents those freezes.

**Closed by Legedric** 2018-03-04 06:52 UTC
Labels: in review

**Comment by GriffinB123** [comment] 2018-03-04 06:55
Sorry for the double conversation on Discord.  I was only able to reproduce the errors while PTM was running.
I am running Binance, 2 bots.  One with 100+ markets, one with around 20 markets.  Was getting the error on both.
Since upgrading my VPS specs, the error frequency seems to have gone down?  Too soon to be sure.

**Comment by statik121** [comment] 2018-03-04 13:25
I’ve had my PTMagic freeze 3 times since yesterday. 2 times it went into Flood Prorection and never came out of it. I found it 2 hours later. 1 time seeemed to just randomly freeze for no reason. Running Windows 2016 Server, 2 processors, 4gb ram on VPS with 10GB connection using Binance and 112 markets. I have 2 instances on the same VPS. 1 running PT Feeder and 1 running PTMagic. Magic is the only app affected. The bots continue to make trades regardless.

**Comment by Legedric** [comment] 2018-03-04 17:37
Thanks to all of you for your feedback. There will be a solution for this in the next release (building the release package right now).
