### ISSUE TITLE
Suggestion - Ability to enable/disable DCA, SOM from PTM web UI

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#366] opened 2018-03-23 12:02 UTC
Can we have an option to enable/disable DCA, SOM from PTM web UI? It possible to enable/disable DCA, SOM based on a schedule (every hour, every 2 hrs, every midnight).

**Comment by Legedric** [comment] 2018-03-23 18:33
This is somehow a duplicate of #365 and #171

**Closed by Legedric** 2018-03-23 18:33 UTC
