### ISSUE TITLE
PT magic is not working for me, better to put it for sell and o have support than fighting with it more than 24 hours and steel not working, no video nothing i eat all the wiki

### ISSUE THREAD

**Issue by wahbalami** [Legedric/ptmagic#53] opened 2018-02-19 22:21 UTC

**Comment by sitespagando** [comment] 2018-02-20 01:41
IT'S WORKING PERFECTLY! I'M USING MORE THAN 28 HOURS WITHOUT PROBLEMS NO! IT'S OK TO INSTALL! Before you go and talk about bullshit, post the print of your difficulty. THE TOOL HERE IS FREE! DEVELOPER IS NOT A DRAWER

**Comment by wahbalami** [comment] 2018-02-20 01:55
dotnet problem i installed and desintalled too many times
![image](https://user-images.githubusercontent.com/36618681/36404141-1197d034-15b7-11e8-8a91-1142797915f5.png)

**Comment by wahbalami** [comment] 2018-02-20 01:55
"dotnet has stopped working"

**Comment by sitespagando** [comment] 2018-02-20 02:01
Please use double backslashes when you are using windows path names.
So please change you settings for PTMagicBasePath to this:

'"PTMagicBasePath": "C:\\Users\\Administrator

**Comment by wahbalami** [comment] 2018-02-20 02:09
already done, i know that

**Comment by sitespagando** [comment] 2018-02-20 02:11
then update core sdk your machine should have bug because ta running normal here

**Comment by wahbalami** [comment] 2018-02-20 03:22
i did that many many times on the day nothing

**Comment by mrkush** [comment] 2018-02-20 04:07
PT and PTmagic  to be in C drive not to sure but its working for me 
"ProfitTrailerPath": "C:\\ProfitTrailer"
"PTMagicBasePath": "C:\\PTMagic"

**Comment by Legedric** [comment] 2018-02-20 05:24
@mrkush Sorry but that's wrong. PT Magic does not need to be located in C:\ The path is there to be adjusted by the user to whatever. My PTM is in fact running on D:\

@wahbalami I added some better logging in that place to find the error. Looks like something is wrong with a market trend in there.

**Comment by Legedric** [comment] 2018-02-20 05:25
Closing this as it is a duplicate of #35

**Closed by Legedric** 2018-02-20 05:25 UTC
