### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by SW-Nicki** [Legedric/ptmagic#261] opened 2018-03-02 03:13 UTC
Did anybody solved the problem now, to run PT Magic on a raspberry?

If would be great to get an installation guide!

There are so many people running PT on a raspberry, it would be really great to have a solution to run PT Magic on it too.............

**Comment by Legedric** [comment] 2018-03-02 03:57
Duplicate of #81

**Closed by Legedric** 2018-03-02 03:57 UTC
