### ISSUE TITLE
Balance prediction blank.

### ISSUE THREAD

**Issue by mfactor50** [Legedric/ptmagic#350] opened 2018-03-21 18:00 UTC
I'm not getting any data on the balance prediction... (sorry for not uploading screen shot last time)
![scrshot](https://user-images.githubusercontent.com/36116249/37728247-aa2520ae-2d31-11e8-8460-b4a062ed9734.png)

**Comment by Legedric** [comment] 2018-03-21 19:11
Duplicate of #316

**Closed by Legedric** 2018-03-21 19:11 UTC
