### ISSUE TITLE
Ability to edit the PTM files in a web editor with a manual pushing of the changes to the PT files.

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#360] opened 2018-03-23 10:10 UTC
I hope there is a way to edit all PTM files such as settings.analyzer.json, pairs file, DCA file, and indicator file saved in the PTM folder.  There should be an option to manually push the changes to the PT files after editing the files.

**Comment by Legedric** [comment] 2018-03-23 11:01
Duplicate of #171

**Closed by Legedric** 2018-03-23 11:01 UTC
