### ISSUE TITLE
Monitor.dll / Frontend not Working properly

### ISSUE THREAD

**Issue by azenator** [Legedric/ptmagic#40] opened 2018-02-19 12:03 UTC
Hi there,

when I'm trying to access the Monitor my Monitor.dll process wents up to 90% CPU load.

I cant access the Dashboard and the Sales analyzer:

Monitor.dll:

![image](https://user-images.githubusercontent.com/35136478/36376783-b9696892-1574-11e8-8212-dde9fb0b7c2a.png)

PTMagic.dll:

![image](https://user-images.githubusercontent.com/35136478/36376794-c8ce75b6-1574-11e8-8556-d84b1bc72a51.png)

Webinterface:

![image](https://user-images.githubusercontent.com/35136478/36376825-e571e658-1574-11e8-8c98-9569d9dcf576.png)

And sometime I get an JSON error at the Sales Analyzer Tab. I've set "StartBalance" manualy. Running in TestMode version 1.0.2 on dotnet 2.3.1 on Ubuntu Linux 

Any ideas?

**Comment by Legedric** [comment] 2018-02-19 12:05
Does your Profit Trailer folder contain a file named "ProfitTrailerData.json"? Because that's the file where PT Magic reads your sales data from. It seems like the path to the fle or the file itself may have cause trouble for whatever reason.

**Comment by azenator** [comment] 2018-02-19 12:08
Yes the ProfitTrailerData.json is located in the PT Dir, the file has 1,7k entries.

`"ProfitTrailerPath": "/home/munin/binance", // Path to your Profit Trailer...`

**Comment by Legedric** [comment] 2018-02-19 12:11
Hmmm maybe that's what is causing the problem here. I have to check how the tool can handle such a huge sales log.

**Comment by innerpartycolt** [comment] 2018-02-19 13:59
I can second this. The problem started after upgrading to 1.0.2 (maybe a coincidence). It worked fine for a few hours, then it started to freeze. I tried to start Magic and Monitor before PT and they did't look 'hungry'. Once I started PT, Monitor consumed 90% of CPU.

**Comment by Legedric** [comment] 2018-02-19 14:08
@innerpartycolt How large is your Sales Log in PT? Is it also that large like the one from azenator=

**Comment by innerpartycolt** [comment] 2018-02-19 14:26
It's big :)

>wc -l ProfitTrailer.log
>396207 ProfitTrailer.log

after renaming the file the situation got better – the VPS is not freezing now. But CPU usage is still at 90%

**Comment by Legedric** [comment] 2018-02-19 14:31
@innerpartycolt  The sales log is not in the log files.
What I mean is the file "ProfitTrailerData.json" or in other words this:
![image](https://user-images.githubusercontent.com/8308141/36382626-ee5e8090-1589-11e8-8e32-2da791ea78ae.png)

**Comment by Legedric** [comment] 2018-02-19 14:41
You are both running PT on Unix systems, right?

**Comment by Legedric** [comment] 2018-02-19 14:56
I was able to reproduce this issue and it has to do with large PT data files. I will see what I can do about that during the next days.

**Comment by innerpartycolt** [comment] 2018-02-19 14:56
I'm sorry, I got confused.

It seems that the sales log consists of only one line, but it's rather big. It had more than 30k characters in it. Once I renamed the file, everything went back to normal.

Yes, I'm running it on Unix.

**Comment by Legedric** [comment] 2018-02-20 04:57
Found and fixed the cause for the slow loading of large PT Data files. Will be fixed in 1.0.3.

**Closed by Legedric** 2018-02-20 04:57 UTC
Labels: bug, confirmed
