### ISSUE TITLE
Forced update?

### ISSUE THREAD

**Issue by bryceyeg** [Legedric/ptmagic#80] opened 2018-02-20 14:38 UTC
Hello,

I noticed that the settings have stopped updating and PTMagic 1.0.2 has stopped working because of the new release. 

Is this what will happen every time you release a new version? Or, is this a one-off because the new release has critical fixes? If the add-on is going to stop working every time there's a new update then that's pretty inconvenient.

Please advise.

Thanks,

Bryce

**Comment by TwixRaider** [comment] 2018-02-20 14:50
No, this is an error caused by the version check itself. Should be fixed with 1.0.3. The version check is just for your information.

**Comment by bryceyeg** [comment] 2018-02-20 14:52
Okay, thanks. :)

**Closed** 2018-02-20 14:53 UTC
