### ISSUE TITLE
couldn't start PTMagic when the license is associated with multiple bots

### ISSUE THREAD

**Issue by efurban** [Legedric/ptmagic#500] opened 2018-05-09 03:43 UTC
Hi, 
I've tried this for a week but still couldn't get it working. 
the current license is tied to two bots, setting names are different.  names are checked and verified with the api (/swagger-ui.html) with no issues.  I event tried saving it (using the api) to different names but all without any success.  Any help or pointer would be greatly appreciated.  

Error message : https://pastebin.com/1qWAiVHH

Thanks.

**Comment by Legedric** [comment] 2018-05-10 08:50
Duplicate of #482

**Closed by Legedric** 2018-05-10 08:50 UTC
