### ISSUE TITLE
Same setting switch

### ISSUE THREAD

**Issue by adamnl** [Legedric/ptmagic#511] opened 2018-05-13 21:39 UTC
Every run I get a switch, even switches to the same setting.

I am running Ubuntu Linux.
Testmode is off.
Flood protection set to 15 minutes.
Not using other tools that change config files such as PT Feeder or anything.

Both PT (initialize folder) and PTM (_presets/Default/) contained the same properties files when starting (not containing PTM PTMagic_xxx headers). Headers are set after first PTM run (PTMagic_ActiveSetting = Default). In PT web gui config and in PTM web gui the active setting is not Default, but Main Currency Trend Critical (PTMagic_ActiveSetting = MainCurrencyTrendCritical)). I run these settings: https://github.com/stevenshizzleh/the-north-star

Noteworthy from logs:

INFO - Checking global settings triggers...
INFO - Checking triggers for 'MainCurrencyTrendCritical'...
INFO - Trigger 'MainCurrency24h' triggered! TrendChange = 9.50%
INFO - Reapply 'MainCurrencyTrendCritical' as the settings.analyzer.json or a preset file got changed.
INFO - Setting 'MainCurrencyTrendCritical' currently active. Checking for flood protection...
INFO - Switching global settings to 'MainCurrencyTrendCritical'...
INFO - Setting 'MainCurrencyTrendCritical' now active!

settings.analyzer.json and the preset files did not change. I checked the last changed date/time.

**Comment by Legedric** [comment] 2018-05-15 12:02
I need some screenshots for this:
1. Screenshot of a "Raid Summary" where this problem occurs. Should look something like this:
![image](https://user-images.githubusercontent.com/8308141/40055515-7094023c-5848-11e8-913c-199ad6711591.png)

2. Screenshot of your PT Config area for your PAIRS file. Should look like this:
![image](https://user-images.githubusercontent.com/8308141/40055536-8dc6a404-5848-11e8-8a84-e9bd1f9305de.png)

**Comment by adamnl** [comment] 2018-05-15 18:33
![raidsum](https://user-images.githubusercontent.com/329443/40076479-3f872fca-587f-11e8-888a-2bd3fe1e6547.png)
![pairsconf](https://user-images.githubusercontent.com/329443/40076480-3f9febbe-587f-11e8-842c-82c9deb53e45.png)

**Comment by Legedric** [comment] 2018-05-18 07:51
No clue why it is happening. Seems like it is not really able to read the current setting from your PT.
As I am not able to reproduce this in any way, I cannot provide a fix for this unfortunately.

**Closed by Legedric** 2018-05-18 07:51 UTC
Labels: waiting for user

**Comment by adamnl** [comment] 2018-05-18 07:56
How is the current setting read? Is it getting the line starting with '# PTMagic_ActiveSetting = '?

**Comment by Legedric** [comment] 2018-05-18 08:19
Yes, correct.

Ah ok so it is reapplying the setting over and over again?
PTM does a check on each run if the Last Write Time of any of your preset or settings files was changed since the last run. So maybe PTM/dotnet is not able to read the proper Last Write Time on your system and starts a reapply every interval?

If so, I have still no clue what may cause this on your system as I know that several PTM users are using Ubuntu and do not face this issue.

**Comment by adamnl** [comment] 2018-05-18 08:33
"so it is reapplying the setting over and over again?"
Correct.

"If so, I have still no clue what may cause this on your system as I know that several PTM users are using Ubuntu and do not face this issue."
I did not have this issue before either.

**Comment by adamnl** [comment] 2018-05-18 08:34
"PTM does a check on each run if the Last Write Time of any of your preset or settings files was changed since the last run."
Which files does it check? The settings.analyzer.json file and which preset files? The ones in the initialization folder?

**Comment by adamnl** [comment] 2018-05-18 08:45
![settings](https://user-images.githubusercontent.com/329443/40225150-8f6b36ac-5a88-11e8-927b-253aa0a21d2d.png)
![presets](https://user-images.githubusercontent.com/329443/40225151-8f7fac18-5a88-11e8-97ba-981990d77973.png)
