### ISSUE TITLE
Switching to default settings every minute

### ISSUE THREAD

**Issue by ADWilkinson** [Legedric/ptmagic#46] opened 2018-02-19 19:26 UTC
Hi,

I have followed the tutorials and managed to get PTMagic working without much hassle which is great. However i've set up my telegram bot and constantly every minute I get a message saying the settings have been switched to "Default". Is there a defect in the sense that if the settings are already default should it be constantly switching to it regardless instead of just doing a check to see what state it's currently in first.

I'm getting no errors from the logs from what I can see so I imagine i set it up correctly. (VPS Ubuntu if that helps)

side note: just want to say a big thank for for creating this addon with the aim of keeping it free - fantastic work and the community appreciates it!

**Comment by TwixRaider** [comment] 2018-02-19 20:47
There is a setting called "FloddProtectionMinutes" in the "settings.general.json" that should prevent this. As a default value it should have 15 minutes. What is the value in your installation?

**Comment by ADWilkinson** [comment] 2018-02-19 20:51
Hi Twix, my settings are set to 15 minutes too which unfortunately doesn't help the case.

I switched the interval of updates of PTMagic to 5 minutes instead of 1 minute and just as I expected the 'resetting to default update' comes every 5 minutes now. Any other ideas?

I've added a screenshot just for clarity of what i'm seeing now 

![image](https://user-images.githubusercontent.com/29403976/36396482-5d0831b8-15b6-11e8-81cc-dc95697884e4.png)

**Comment by jamesblackjr** [comment] 2018-02-19 21:21
Mine was doing the same thing, I had to turn it off.  Hopefully, we can get a setting to only notify if the setting changes.

**Comment by buschjost** [comment] 2018-02-19 21:57
Are you in Test mode? Then it seems to behave this way.

**Comment by jamesblackjr** [comment] 2018-02-19 22:55
I was in Test mode before I turned it off, let me turn it back on while in live mode.

**Comment by jamesblackjr** [comment] 2018-02-19 23:07
Nope, it still does in in live mode.

**Comment by Zamboniman** [comment] 2018-02-20 05:03
Mine was doing the same thing. Not in test mode. I had to turn it off as well. I hope this gets fixed.

**Comment by Legedric** [comment] 2018-02-20 05:09
Usually it does exactly that. I have to figure out what is wrong with your instance as I never had that prohblem.

When you run PT Magic, does it actually change your PT files? Like at least changing the header and adding some comments from PT Magic to it?

**Comment by ADWilkinson** [comment] 2018-02-20 20:45
Sorry for the late reply, yep PT Magic works absolutely perfectly with exception to this one telegram bug. I don't think its the bot though but rather the reason why the files are being written every 1 minute (or 5 minutes now)

**Comment by Spottycat** [comment] 2018-02-20 22:02
I can confirm that every run of the bot sends out a telegram message, even if no other setting ism eing selected. Running version 1.0.3 on Linux Ubuntu.

**Comment by Zamboniman** [comment] 2018-02-21 04:59
Well, the monitor shows the settings being updated each and every minute as well, synchronized with 'last runtime', so it's definitely missing out that the settings are *already* in a particular state.

**Comment by Legedric** [comment] 2018-02-21 05:27
Can someone having that issue please post the header that PT Magic writes to their PAIRS.PROPERTIES file in the Profit Trailer/trading directory?
Because that's where the "check for active setting" happens.

**Comment by Ridonia** [comment] 2018-02-21 07:07
If I don't get you wrong, there is no header in pairs.properties
PTMagic is changing values, but doesn't write a header .

It only writes some kind of headers, where it changes the values.
like this:
# PTMagic_SingleMarketSettings - Written on 21/02/2018 08:04:19
# ########################################################################

**Comment by Zamboniman** [comment] 2018-02-21 07:17
No header, currently using my default settings, it's just that this gets 'updated' to my default settings each minute, as indicated in the Monitor (synchronized with refresh) and of course as spammed to my telegram bot each minute when that's turned on.

The only indication in the pairs file is, as @Ridonia said above, the following:

# PTMagic_SingleMarketSettings - Written on 2/21/18 12:16:06 AM
# ########################################################################

**Comment by Legedric** [comment] 2018-02-21 13:26
Ok that's interesting. Please upload your settings.analyzer.json file here so I can see what is configured in there.

**Comment by Ridonia** [comment] 2018-02-21 13:31
Guess it's the standard wich comes with PTM
`﻿{
  "AnalyzerSettings": {
    "MarketAnalyzer": {
      "StoreDataMaxHours": 24, // Number of hours to store market data
      "IntervalMinutes": 1, // Interval in minutes for PTMagic to check market trends and triggers
      "ExcludeMainCurrency": true, // Excludes the main currency (for example BTC) from market trend analysis
      "MarketTrends": [
        {
          "Name": "CMC24h", // UNIQUE market trend name (to be referenced by your triggers below)
          "Platform": "CoinMarketCap", // Platform to grab prices from (Allowed values are: CoinMarketCap, Exchange)
          "MaxMarkets": 50, // Number of markets/pairs to analyze sorted by 24h volume
          "TrendMinutes": 1440 // Number of minutes to build a trend (1440 = 24h, 720 = 12h, 60 = 1h)
        },
        {
          "Name": "Exchange1h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 60,
          "TrendCurrency": "Market" // Trend Currency to build the trend against. If set to "Fiat", the trend will take the USD value of your main currency into account to build the trend. (Allowed values are: Fiat, Market)
        },
        {
          "Name": "Exchange12h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 720,
          "TrendCurrency": "Market"
        },
        {
          "Name": "Exchange24h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 1440,
          "TrendCurrency": "Market"
        }
      ]
    },
    "GlobalSettings": [ // Global settings for Profit Trailer properties
      {
        "SettingName": "EndOfTheWorld", // UNIQUE name of your setting
        "TriggerConnection": "AND", // Define if triggers will be connected by AND or OR
        "Triggers": [ // Your triggers for this setting
          {
            "MarketTrendName": "Exchange1h", // Reference to the market trend specified above
            "MaxChange": 0 // Maximum trend change % for this setting to get triggered
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": -1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -5
          }
        ],
        "PairsProperties": { // Properties for PAIRS.PROPERTIES
          "ALL_sell_only_mode": true,
          "ALL_trailing_profit": 0.1
        },
        "DCAProperties": { // Properties for DCA.PROPERTIES
          "trailing_profit": 0.1
        }
      },
      {
        "SettingName": "TankingDown",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -3,
            "MinChange": -5
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -1.1,
          "ALL_trailing_buy": 0.39,
          "ALL_trailing_profit": 0.1
        },
        "DCAProperties": {
          "trailing_buy": 0.1
        }
      },
      {
        "SettingName": "BearSighted",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -0.9,
          "ALL_trailing_profit": 0.15
        },
        "DCAProperties": {
          "trailing_profit": 0.15
        }
      },
      {
        "SettingName": "ReadyForLiftOff",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": -1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 1,
            "MaxChange": 3
          }
        ],
        "PairsProperties": {
          "ALL_trailing_buy": 0.2,
          "ALL_sell_value": 1.1
        },
        "DCAProperties": {
          "sell_value": 1.1
        }
      },
      {
        "SettingName": "ToTheMoon",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 3
          }
        ],
        "PairsProperties": {
          "ALL_trailing_buy": 0.15,
          "ALL_sell_value": 1.3
        },
        "DCAProperties": {
          "sell_value": 1.3
        }
      },
      {
        "SettingName": "Default",
        "PairsProperties": {
          "File": "PAIRS.PROPERTIES"
        },
        "DCAProperties": {
          "File": "DCA.PROPERTIES"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.PROPERTIES"
        }
      }
    ],
    "SingleMarketSettings": [ // Single market/pair settings for Profit Trailer properties
      {
        "SettingName": "PumpNDumpProtection",
        "TriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Relative", // The relation of the single market trend. Relative = Single market trend compared relative to the market trend / Absolute = Single market trend viewn on its own
            "MinChange": 10
          },
          {
            "MarketTrendName": "Exchange12h",
            "MarketTrendRelation": "Relative",
            "MinChange": 10
          },
          {
            "MarketTrendName": "Exchange24h",
            "MarketTrendRelation": "Relative",
            "MinChange": 10
          }
        ],
        "PairsProperties": {
          "ALL_trailing_profit_OFFSETPERCENT": -10,
          "ALL_sell_value_OFFSETPERCENT": -30,
          "ALL_sell_only_mode": true,
          "ALL_DCA_enabled": false
        }
      },
      {
        "SettingName": "FreefallBlock",
        "TriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": -5
          }
        ],
        "PairsProperties": {
          "ALL_trailing_profit_OFFSETPERCENT": -10,
          "ALL_sell_value_OFFSETPERCENT": -30,
          "ALL_sell_only_mode": true,
          "ALL_DCA_enabled": false
        }
      }
    ]
  }
}`

**Comment by Legedric** [comment] 2018-02-21 13:43
Checking on that, thanks.

**Comment by Zamboniman** [comment] 2018-02-21 14:12
Mine too is the default.

**Comment by Legedric** [comment] 2018-02-21 14:55
Does the pairs properties file in _presets/default have any headers from PT Magic?

**Comment by Ridonia** [comment] 2018-02-21 16:05
@Legedric No

**Comment by Legedric** [comment] 2018-02-21 16:11
Ok thanks, I am getting closer :)

When you stop PT Magic and start it again, do you see log entries for lines like this?
- Checking automated settings for presets...
- Prepared pairs.properties for 'default'

Right at the beginning somewhere?

**Comment by Ridonia** [comment] 2018-02-21 16:23
Yes, seems ok 

> 1|PTMagic  | 2018/02/21 17:20:54.046 INFO - DCA.properties found! 
1|PTMagic  | 2018-02-21 17:20 +01:00: 2018/02/21 17:20:54.046 INFO - Checking for Indicators Properties file 
1|PTMagic  | 2018-02-21 17:20 +01:00: 2018/02/21 17:20:54.046 INFO - INDICATORS.properties found! 
1|PTMagic  | 2018/02/21 17:20:54.046 INFO - Checking automated settings for presets... 
1|PTMagic  | 2018-02-21 17:20 +01:00: 2018/02/21 17:20:54.056 INFO - Prepared PAIRS.PROPERTIES for 'Default' 
1|PTMagic  | 2018-02-21 17:20 +01:00: 2018/02/21 17:20:54.056 INFO - Prepared DCA.PROPERTIES for 'Default' 
1|PTMagic  | 2018/02/21 17:20:54.056 INFO - Prepared INDICATORS.PROPERTIES for 'Default' 
1|PTMagic  | 2018-02-21 17:20 +01:00: 2018/02/21 17:20:54.091 INFO - Checking market trends every 1 minutes...

**Comment by Legedric** [comment] 2018-02-21 16:47
Does your pairs file in _presets now have a header?

**Comment by Legedric** [comment] 2018-02-21 20:23
This should be fixed in version 1.0.4. If not, please reopen this issue!

**Comment by Legedric** [comment] 2018-02-22 13:43
Ok after the latest fix did not fully resolve this please answer the following questions:
- OS of your system
- Exchange
- Market
- Does your pairs.properties located in _presets/Default have any PT Magic specific headers at the TOP of the file?
- Does your pairs.properties located in ProfitTrailer/trading have any PT Magic specific headers at the TOP of the file?

Thanks!

**Comment by ADWilkinson** [comment] 2018-02-22 13:54
OS: Ubuntu 16.04
Exchange: Binance
Market: BTC

Current header :
`##################  PAIRS.properties ##############################
################### VERSION CONTROL ###############################
###################################################################
### Read the wiki for more explanations about the properties    ###
### https://wiki.profittrailer.io                               ###
###################################################################
###################################################################

#++++++++++++++++++++#
#INITIAL BUY SETTINGS#
#++++++++++++++++++++#`

Very similar header in the pairs.properties folder.

Hope that helps @Legedric !

**Comment by Zamboniman** [comment] 2018-02-22 15:02
For me:

OS: Arch Linux

Exchange: Binance

Market: Does it in all three, BTC, ETH, and USDT

No, the pairs properties in _presets/Default doesn't have any PT Magic headers

No, the pairs file in ProfitTrailer/trading doesn't have any PT Magic headers

**Comment by Mirko1080** [comment] 2018-02-22 17:51
OS: **Ubuntu 16.04.3**
Exchange: **Binance**
Market: **BTC**
Does your pairs.properties located in _presets/Default have any PT Magic specific headers at the TOP of the file?  **No**
Does your pairs.properties located in ProfitTrailer/trading have any PT Magic specific headers at the TOP of the file? **No**
**I am currently in 'Default' global setting**

**Comment by Legedric** [comment] 2018-02-22 19:31
@Zamboniman and @Mirko1080 
When you stop PT Magic and start it again, do you see something like:
- Checking automated settings for presets
- Prepared pairs.properties for default

etc.?

Please double check if the file names listed here in your settings.analyzer.json:
```
{
        "SettingName": "Default",
        "PairsProperties": {
          "File": "PAIRS.PROPERTIES"
        },
        "DCAProperties": {
          "File": "DCA.PROPERTIES"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.PROPERTIES"
        }
      }
```

Do exists in "_presets/Default" (take nore: Case sensitive!)
If your files have the ending .properties (small letters), try changing that in your settings.analyzer.json

I thinks this is the problem here as it seems to be a Unix issue with case sensitive file names. Usually it shoueldn do that in PT Magic but you never know :)

**Comment by Mirko1080** [comment] 2018-02-22 20:19
So I modified that piece of code in **settings.analyzer.json** like this:
```
{
        "SettingName": "Default",
        "PairsProperties": {
          "File": "PAIRS.properties"
        },
        "DCAProperties": {
          "File": "DCA.properties"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.properties"
        }
      }
```
And that fixed my problem, thanks @Legedric .

**Comment by ADWilkinson** [comment] 2018-02-23 00:25
Can confirm that this fixed the constant telegram spam messaging for me

**Comment by Zamboniman** [comment] 2018-02-23 00:58
>When you stop PT Magic and start it again, do you see something like:
>
>Checking automated settings for presets
>Prepared pairs.properties for default

Yes to both.

>Please double check if the file names listed here in your settings.analyzer.json:

Yes, they're there.

>Do exists in "_presets/Default" (take nore: Case sensitive!)
If your files have the ending .properties (small letters), try changing that in your settings.analyzer.json

And you think we found the problem. They're copied over from my ProfitTrailer directory, where the ".properties" portion is smallcase.

>I thinks this is the problem here as it seems to be a Unix issue with case sensitive file names. Usually it shoueldn do that in PT Magic but you never know :)

Yup, in Linux PAIRS.PROPERTIES is a different file from PAIRS.properties.

Glad we finally seemed to have tracked this down. I'll make the changes now, and let you know if it *doesn't* fix the problem, but since I see above that it did for others, I'm sure this'll work.

**Comment by Zamboniman** [comment] 2018-02-23 01:07
Yup, now my Monitor reads:

Last Runtime: 1m 3sec ago

Last Settings Switch: 5m 42s ago

Before they were always synchronized.

I'll go ahead and risk turning my telegram bot messaging back on.

**Comment by Legedric** [comment] 2018-02-23 05:09
Thank you, I will fix this problem with the next release so it doesn't matter if you spacify the file names with capital or small letters.

If everything else is working this seemed to be the very last relict of files being loaded with a wrong/case sensitive filename.

**Closed** 2018-02-23 06:59 UTC
Labels: in review
