### ISSUE TITLE
libcurl with opensllerror

### ISSUE THREAD

**Issue by Zamboniman** [Legedric/ptmagic#463] opened 2018-04-27 02:41 UTC
I'm unable to run PTMagic 1.6.1

Upon upgrading and attempting to run it I receive the following error:

>Unhandled Exception: System.PlatformNotSupportedException: The handler does not support custom │
handling of certificates with this combination of libcurl (7.59.0) and its SSL backend ("OpenSS│
L/1.1.0g").

You will note this is with openssl.

I am unsure how to proceed from here.

**Comment by Zamboniman** [comment] 2018-04-27 02:52
This is on Linux BTW.

I found the following as a response to someone else making the suggestion to ensure a version of libcurl is using openssl:

>That doesn't fix the issue, though:

>Unhandled Exception: System.PlatformNotSupportedException: The handler does not support client authentication certificates with this combination of libcurl (7.58.0) and its SSL backend("OpenSSL/1.0.2n").

A response was the following (mac related):

>I did more digging and unfortunately the story is currently weird.

>If you need to just skip client certificates on your dev environment (Mac) for developer-only! purposes, then you can use DangerousAcceptAnyServerCertificateValidator - that should work with any Libcurl combo.
If you truly need custom client certificates support on Mac, then unfortunately neither libuclr+OpenSSL10 won't help as we switched to Apple native crypto APIs in 2.0 (#19718 is not implemented). Given #19718 cost (non-trivial), we recommend to rely on SocketsHttpHandler (aka ManagedHandler) in 2.1 (likely as opt-in) to work around the problem.

>Please let me know if the first dev-only workaround works for you.
Overall we should close this issue as duplicate of #26446, unless there is evidence this problem is different. 

> Thanks!

This discussion was here:

https://github.com/dotnet/corefx/issues/27000

**Comment by Legedric** [comment] 2018-04-27 03:14
Duplicate of #463

**Closed by Legedric** 2018-04-27 03:14 UTC

**Comment by Zamboniman** [comment] 2018-04-27 03:25
Well, not quite  duplicate, no. This one has the error *with* openssl, so it's not the same.

**Comment by Zamboniman** [comment] 2018-04-27 03:44
The new preview version of dotnet-2.1.0, seems to have solved this issue.

For Linux, I recommend upgrading dotnet to the beta version. If not available in your distro you'll need to download and install it manually. Instructions for this are in Issue 65, but update the files accordingly.
