### ISSUE TITLE
Monitor settings

### ISSUE THREAD

**Issue by Ilikebigbots** [Legedric/ptmagic#213] opened 2018-02-26 15:04 UTC
Hi, my settings options have disappearred from my PT magic monitor.
![screenshot 2018-02-26 15 01 09](https://user-images.githubusercontent.com/36853517/36677447-10c243fc-1b06-11e8-8f3e-880ad4ccc64c.png)

**Comment by Legedric** [comment] 2018-02-26 15:05
Duplicate of #212

**Closed by Legedric** 2018-02-26 15:05 UTC
