### ISSUE TITLE
add reverse proxy basepath support

### ISSUE THREAD

**Issue by Baconqueror** [Legedric/ptmagic#60] opened 2018-02-20 00:18 UTC
Hi there,

first of all - great work guys!  I'm running ptmagic behind an nginx reverse proxy. However, I'd like to see ptmagic proxied to a subdirectory, like so:

```
        location /ptmagic/ {
        rewrite ^/ptmagic(/.*)$ $1 break;
        auth_basic "Who?";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

This works great, but any link I click in ptmagic takes me back to https://xxx.domain.tld/ instead of https://xxx.domain.tld/ptmagic/

Long story short, could you add something like a basepath option for the webserver?

**Comment by calebcall** [comment] 2018-02-20 03:15
Here's an nginx config that will make that work :)

`## PTMagic
    location /PTMagic/ {
        auth_basic_user_file /etc/nginx/.htpasswd;
        sub_filter '<a href="/" class="waves-effect"><i class="fa fa-dashboard fa-2x">' '<a href="./" class="waves-effect"><i class="fa fa-dashboard fa-2x">';        
        sub_filter '<a href="/DCACalculator"' '<a href="./DCACalculator"';
        sub_filter '<a href="/SalesAnalyzer"' '<a href="./SalesAnalyzer"';
        sub_filter '<a href="/MarketTrends"' '<a href="./MarketTrends"';
        sub_filter '<a href="/Donate"' '<a href="./Donate"';
        proxy_pass http://localhost:5000/;
    }`

It does nothing with the headers so you don't need to add all the extra headers.  I've also already logged a bug about this and it's going to be fixed.  The reason is some paths are absolute and others are relative, all should be relative.

**Comment by Legedric** [comment] 2018-02-20 05:33
Closing as duplicate of #28

**Closed by Legedric** 2018-02-20 05:33 UTC
