### ISSUE TITLE
Fresh install of 1.6.1 exit wih code [0] via signal 

### ISSUE THREAD

**Issue by jwk27** [Legedric/ptmagic#491] opened 2018-05-06 10:32 UTC
I just did a fresh install and when I start PTMagic I get the following error
my server specs= Ubuntu ver 28
PT = 2.0.2
PTMagive version = 1.6.1

9|PTMagic  | 2018-05-06 10:29 +00:00:
9|PTMagic  | Unhandled Exception:
9|PTMagic  | 2018-05-06 10:29 +00:00: System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.58.0) and its SSL backend ("OpenSSL/1.1.0g").
9|PTMagic  |    at System.Net.HttpWebRequest.GetResponse()
9|PTMagic  |    at Globals.SystemHelper.UrlIsReachable(String url) in D:\Tools\PTMagic\Globals\SystemHelper.cs:line 810
9|PTMagic  |    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 168
9|PTMagic  | 2018-05-06 10:29 +00:00:
PM2        | App [PTMagic ETH] with id [9] and pid [32565], exited with code [0] via signal [SIGABRT]

**Comment by Legedric** [comment] 2018-05-06 10:41
Duplicate of #450

**Closed by Legedric** 2018-05-06 10:41 UTC
